#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [5]:
data_path = '../data/supermarket_sales.csv'
df = pd.read_csv (data_path)

In [6]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [9]:
df.groupby ('Branch') ['gross income']. sum (). sort_values (ascending = False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [14]:
# variant with pivot table
result1 = pd.pivot_table (df, index = 'City', columns = 'Branch', values = 'gross income', aggfunc = 'sum')

In [16]:
result1

Branch             A         B          C
City
Mandalay         NaN  5057.032        NaN
Naypyitaw        NaN       NaN  5265.1765
Yangon     5057.1605       NaN        NaN

In [18]:
# variant with group by
df.groupby ('City') ['gross income']. sum ().sort_values (ascending = False)

City
Naypyitaw    5265.1765
Yangon       5057.1605
Mandalay     5057.0320
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [21]:
invoice_by_category = pd.pivot_table (df, index = 'Branch', columns = 'Product line', values = 'Invoice ID', aggfunc = 'count')

In [22]:
invoice_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [31]:
invoice_by_category ['Electronic accessories'].sort_values (ascending = False)

Branch
A    60
B    55
C    55
Name: Electronic accessories, dtype: int64

In [37]:
invoice_by_category ['Electronic accessories'].nlargest(1)

Branch
A    60
Name: Electronic accessories, dtype: int64

In [36]:
col = invoice_by_category['Electronic accessories']

max_value = col.max()
max_index = col.idxmax()

print(max_index, max_value)

A 60

In [38]:
invoice_by_category ['Electronic accessories'].sort_values (ascending = False).head (1)

Branch
A    60
Name: Electronic accessories, dtype: int64

In [40]:
invoice_by_category ['Electronic accessories'].sort_values (ascending = False).iloc[0]

np.int64(60)

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Проаналізувати кількість покупок зроблених різними типами клієнтів по містах

In [48]:
invoice_customer_type = pd.pivot_table (
    df, 
    index = 'City', 
    columns = 'Customer type', values = ['Invoice ID', 'Total'] , 
    aggfunc = {'Invoice ID': 'count', 'Total': 'mean'}
)
invoice_customer_type

              Invoice ID              Total
Customer type     Member Normal      Member      Normal
City
Mandalay             165    167  325.482945  314.329257
Naypyitaw            169    159  336.575636  337.656755
Yangon               167    173  321.182488  303.831763

Результат показує що найбільша кількість покупок здійснена членами мережі в магазинах міста Naypyitaw, і середній чек для членів мережі в цьому місті також найвищий. Але середній чек звичайних клієнтів в цьому місті все ж таки більший і це єдине місто з такою ситуацією. Найнижчий середній чек  і найменша кількість покумопк здійснених членами мережі в місті Yangon. Але тут середній чек членів мережі відчутно більший за середній чек звичайних клієнтів.  Таким чином: 
1. В місті Naypyitaw потрібно робити додаткові пропозиції для членів мережі з метою підвищення їхнього середнього чеку. Вні хоч і найбільший по мічстах, але менший за середній чек звичайних клієнтів.
2. В місті Yangon кількість покупок здійснених звичайними клієнтами найбільша по містах, але середній чек найменший. Одже тут потрібно залучати звичайних клієнтів приєднуватись до членів мережі, надаючи додаткові переваги. Адже члени мережі зазвичай при реєстрації надають певну інформацію про себе, що допомагає в майбутньому аналізу клієнтської бази. А також поронувати всіх групами клієнтів додаткові акційні товари для підвищення середнього чеку покупки.
3. і т.д.

2. Покупки здійснені покупцями різних гендерів за категоріями

In [59]:
df.groupby (['City', 'Product line']) ['Invoice ID']. agg ('size')

City       Product line
Mandalay   Electronic accessories    55
           Fashion accessories       62
           Food and beverages        50
           Health and beauty         53
           Home and lifestyle        50
           Sports and travel         62
Naypyitaw  Electronic accessories    55
           Fashion accessories       65
           Food and beverages        66
           Health and beauty         52
           Home and lifestyle        45
           Sports and travel         45
Yangon     Electronic accessories    60
           Fashion accessories       51
           Food and beverages        58
           Health and beauty         47
           Home and lifestyle        65
           Sports and travel         59
Name: Invoice ID, dtype: int64

In [60]:
pivot_city_category = pd.pivot_table(
    df,
    index="City",
    columns="Product line",
    values="Invoice ID",
    aggfunc="size",
    fill_value=0
)

pivot_city_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
City,,,,,,
Mandalay,55,62,50,53,50,62
Naypyitaw,55,65,66,52,45,45
Yangon,60,51,58,47,65,59

Розбивка кількості покупок різних категорій товарів по містах дає зрозуміти що в різних містах картина відрізняється. Електроні товари продаються найбільше в місті Yangon? Fashion accessories в місті Naypyitawб спорт товари найактивніше купляють у місті Mandalay. на основі цих даних можна в магазинах міста промоутити певні групи товарів більше або менше, або щоб деякі групи товарів продавались більше або їх виставляти десь в торгівельних залах у більш проходимих місцях, або пропонувати акції на них. або щоб не залужавався товар певних категорій його давати як подарунок за певну суму в чеку і т.д.

3. аналіз покупок по дням тижня

In [61]:
# перш ніж працювати з запитом перевіримо тип потрбної колонки
df['Date'].dtype

In [64]:
# міняємо рядковий тип на потрібний для подальших перетворень
df['Date'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")

In [65]:
# перевіряємо чи змінився тип
df['Date'].dtype

dtype('<M8[us]')

In [66]:
# створюємо колонку з назвою дня тижня
df['Day'] = df['Date'].dt.day_name()

In [68]:
df [['Date', 'Day']]. head()

        Date       Day
0 2019-01-05  Saturday
1 2019-03-08    Friday
2 2019-03-03    Sunday
3 2019-01-27    Sunday
4 2019-02-08    Friday

In [69]:
# створюємо півот тейбл для подальшого аналізу по днях
summary = pd.pivot_table(
    df,
    index='Day',
    values=['Invoice ID', 'Total'],
    aggfunc={
        "Invoice ID": 'count',
        "Total": ['sum', 'mean']
    }
)
summary

          Invoice ID       Total
               count        mean         sum
Day
Friday           139  316.016838  43926.3405
Monday           125  303.192624  37899.0780
Saturday         164  342.200058  56120.8095
Sunday           133  334.269868  44457.8925
Thursday         138  328.617739  45349.2480
Tuesday          158  325.836997  51482.2455
Wednesday        143  305.812133  43731.1350

In [70]:
summary.columns = ["Orders", "Revenue", "Avg_Check"]
summary

           Orders     Revenue   Avg_Check
Day
Friday        139  316.016838  43926.3405
Monday        125  303.192624  37899.0780
Saturday      164  342.200058  56120.8095
Sunday        133  334.269868  44457.8925
Thursday      138  328.617739  45349.2480
Tuesday       158  325.836997  51482.2455
Wednesday     143  305.812133  43731.1350

In [72]:
# змінюємо порядок днів тижня
order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
summary = summary.reindex(order)

summary

           Orders     Revenue   Avg_Check
Day
Monday        125  303.192624  37899.0780
Tuesday       158  325.836997  51482.2455
Wednesday     143  305.812133  43731.1350
Thursday      138  328.617739  45349.2480
Friday        139  316.016838  43926.3405
Saturday      164  342.200058  56120.8095
Sunday        133  334.269868  44457.8925

Згідно з данимив таблиці бачимо, що найактивніший день покупок це субота, найменше покупок здійсеюють в понеділок. При цьому в суботу є і навищий середній чек. Це повязано з тим, що в вихідний день лбюди більше приділяють увагу закупам на тиждень. Тобто на суботу потрібно щоб були відповідні запаси товарів, можна більше виставляти товарів нових або тих, що гірше продаються. Відповідно в понеділок, коли продажі менші і по кількості і по сумах чеків можна пропонувати клієнтам вигідні пропозиція дня. і т.д.

Можна додатково зробити розбивку ще і по годинах доби і днях

In [74]:
df ['Time'].dtype

In [75]:
df['Hour'] = pd.to_datetime(df['Time'], format="%H:%M").dt.hour

In [77]:
df [['Day', 'Hour']]. head()

        Day  Hour
0  Saturday    13
1    Friday    10
2    Sunday    13
3    Sunday    20
4    Friday    10

In [81]:
# створюємо півот тейбл для подальшого аналізу по днях
summary_hour = pd.pivot_table(
    df,
    index = 'Day',
    columns = 'Hour',
    values = 'Invoice ID',
    aggfunc = 'count'
)
summary_hour

Hour       10  11  12  13  14  15  16  17  18  19  20
Day
Friday     18  11  10  16  14  18  10   6  11  13  12
Monday     12   9  14  10   6  18  16  11  11   8  10
Saturday   16  12  18  14  11  12  14  12  18  23  14
Sunday     11  11  11  18  13  11   6  11  15  17   9
Thursday   18  15  11  12  14  12  12  15   9  10  10
Tuesday    16  20  11  13  15  14   9   9  12  28  11
Wednesday  10  12  14  20  10  17  10  10  17  14   9